services:
  - type: web
    name: thread-count-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn thread_count_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
    plan: free